config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :watch_items, only: [:edit, :create, :update, :index, :destroy]
  resources :orders
  resources :bids
  resources :pending_bids, only: [:create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/all_items', to: 'items#index'
  
  root 'staticpages#index'
  
  resources :stores
  
  namespace :stores, as: :store, path: '/:store' do 
    resources :items
  end
end

app/models/store.rb
class Store < ActiveRecord::Base  
  validates :name, uniqueness: true,
                   presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  has_many :items

  def generate_slug
    self.slug = name.parameterize
  end

  def self.sort_all
    order(:name)
  end
end

app/controllers/stores/items_controller.rb
class Stores::ItemsController < Stores::StoresController
  
  def index
    @items = Item.where(store_id: current_store.id).paginate(:page => params[:page], :per_page => 8)
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @categories = Category.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "Item has been created!"
      redirect_to store_items_path
    else
      flash.now[:errors] = @item.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def edit 
    @item = current_user.store.items.find(params[:id])
    @categories = Category.all
  end
  
  def update
    @item = current_user.store.items.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Item has been updated!"
      redirect_to store_items_path
    else
      flash.now[:errors] = @item.errors.full_messages.join(", ")
      render :edit
    end
  end
  
  def destroy
    item = current_user.store.items.find(params[:id])
    if item.bids.empty?
      item.delete
      flash[:success] = "Item has been deleted!"
      redirect_to store_items_path
    else
      flash[:errors] = "That item has bids! It can't be deleted."
      redirect_to store_items_path
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, 
                                 :description, 
                                 :active,
                                 :starting_price, 
                                 :expiration_date, 
                                 :attachment, 
                                 :category_id, 
                                 :store_id)
  end
end

app/controllers/stores/stores_controller.rb
class Stores::StoresController < ApplicationController
  helper_method :current_store
  
  def current_store
    @current_store ||= Store.find_by(slug: params[:store])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  def index
    @stores = Store.paginate(:page => params[:page], :per_page => 8)
  end
  
  def new
    @store = Store.new
  end
  
  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:success] = "Store was successfully created."
      redirect_to stores_path
    else
      flash.now[:errors] = @store.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def edit
    @store = Store.find(params[:id])
  end
  
  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      flash[:success] = "Store was successfully updated."
      redirect_to store_items_path(store: @store.slug)
    else
      flash.now[:errors] = @store.errors.full_messages.join(", ")
      render :edit
    end
  end
  
  def destroy
    store = Store.find(params[:id])
    store.delete
    flash[:success] = "Store was successfully deleted."
    redirect_to stores_path
  end

  private
  
  def store_params
    params.require(:store).permit(:name)
  end
end

app/helpers/stores/items_helper.rb
module Stores::ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/stores/edit.html.erb
<div class="container">
  <h1 class="watch-list-header">Update Store</h1>
  <div class="stitched watch-list">
    <%= render 'form' %>
  </div>
</div>

app/views/stores/index.html.erb
<div class="row">
  <div class="col-md-12 store-column">
    <h1 id="stores-header" >Shop eBiddable Merchants</h1>
  </div>
</div>

<div class="container">
  <% @stores.each_slice(4) do |four_stores| %>
    <div class="row">
      <% four_stores.each do |store| %>
        <div class="col-md-3">
          <div class="well">
            <h5 class="items-title"><%= link_to store.name, store_items_path(store: store.slug) %></h5>
            <% if !store.items.empty? %>
            <%= link_to image_tag(store.items.first.attachment.url, width: "300", class: "image-border"), store_items_path(store: store.slug) %>
            <% end %>
            <% if platform_admin? %>
            <br><%= link_to "Edit", edit_store_path(id: store.id) %>
            <br><%= link_to "Delete", store_path(id: store.id), method: "delete" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/stores/new.html.erb
<div class="container">
  <h1 class="watch-list-header">New Store</h1>
  <div class="stitched watch-list">
    <%= render 'form' %>
  </div>
</div>