config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :watch_items, only: [:edit, :create, :update, :index, :destroy]
  resources :orders
  resources :bids
  resources :pending_bids, only: [:create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/all_items', to: 'items#index'
  
  root 'staticpages#index'
  
  resources :stores
  
  namespace :stores, as: :store, path: '/:store' do 
    resources :items
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates :user_id, presence: true
  validates :item_id, presence: true, uniqueness: true
  validates :total, presence: true
  
  def item
    Item.find(item_id)
  end
  
  def user 
    User.find(user_id)
  end

  def store_owner_email
    if !user.nil?
      user = User.find_by(store_id: item.store.id)
      user.email
    end
  end
  
  def self.create_order
    counter = 0
    
    Item.where(paid: false).each do |item|
      if item.expired? && Bid.find_by(item_id: item.id)
        user_id = item.highest_bidder_id
        price = item.highest_bid
        order = Order.create(user_id: user_id, item_id: item.id, total: price)
        BidMailer.winning_email(order.user, order).deliver_now

        if !order.store_owner_email.nil?
          BidMailer.store_owner_email(order).deliver_now
        end

        counter += 1
      end
    end
    puts "#{Time.now}: #{counter} orders created."
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all
  end

  def edit
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params["order"]["status"])
    redirect_to admin_orders_path
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    if current_user
      @orders = Order.where(user_id: current_user.id)
    else
      flash[:errors] = "Must be logged in to view orders"
      redirect_to login_path
    end
  end
end

app/views/admin/orders/edit.html.erb
<div class="container">
  <%= render :partial => 'layouts/admin_login_header.html.erb' %>
  <%= render :partial => 'layouts/sitewide_header.html.erb' %>

  <div class="stitched">
    <%= form_for [:admin, @order] do |f| %>

      <%= f.label "user_id" %>
      <%= f.text_field "user_id" %>

      <%= f.label "status" %>
      <%= f.text_field "status" %>

      <%= f.label "total" %>
      <%= f.text_field "total" %>

      <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name) %><br>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">

  <%= render :partial => 'layouts/admin_login_header.html.erb' %>
  <%= render :partial => 'layouts/sitewide_header.html.erb' %>

  <h1>All Orders</h1>

  <div class="stitched">
    <h3>Ordered</h3>
    <% @orders.ordered.each do |order| %>
      <div class="all_orders">

        <%= link_to order.id, admin_order_path(order) %> | <%= Order.user_name(order) %> | <%= order.status %>

        <%= form_for order, url: admin_order_path(order) do |f| %>
          <%= f.collection_select(:status, order.statuses, :to_s, :to_s)%><br>
          <%= f.submit %>
        <% end  %>
      </div>
    <% end %>
  </div>
  <br/>

  <div class="stitched">
    <h3>Paid</h3>
    <% @orders.paid.each do |order| %>
      <div class="all_orders">
        <%= link_to order.id, admin_order_path(order) %>
        <%= order.status %>

        <%= form_for order, url: admin_order_path(order) do |f| %>
          <%= f.collection_select(:status, order.statuses, :to_s, :to_s)%><br>
          <%= f.submit %>
        <% end  %>
      </div>
    <% end %>
  </div>
  <br/>

  <div class="stitched">
    <h3>Completed</h3>
    <% @orders.completed.each do |order| %>
      <div class="all_orders">
        <%= link_to order.id, admin_order_path(order) %>
        <%= order.status %>
          <%= form_for order, url: admin_order_path(order) do |f| %>
          <%= f.collection_select(:status, order.statuses, :to_s, :to_s)%><br>
          <%= f.submit %>
          <% end  %>
      </div>
    <% end %>
  </div>

  <br/>
  <div class="stitched">
    <h3>Cancelled</h3>
    <% @orders.cancelled.each do |order| %>
      <div class="all_orders">
        <%= link_to order.id, admin_order_path(order) %>
        <%= order.status %>
        
        <%= form_for order, url: admin_order_path(order) do |f| %>
          <%= f.collection_select(:status, order.statuses, :to_s, :to_s)%><br>
          <%= f.submit %>
        <% end  %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <%= render :partial => 'layouts/admin_login_header.html.erb' %>
  <%= render :partial => 'layouts/sitewide_header.html.erb' %>

  <div class="stitched">
    <% @order.beers.each do |beer| %>
      <% OrderBeer.quantities(beer.id, @order.id).each do |ob| %>
        <%= ob.quantity %>
        <%= link_to beer.name, beer_path(beer) %>
        subtotal: <%= number_to_currency(OrderBeer.line_item_subtotal(beer.price, ob.quantity.to_i)) %></br>
      <% end %>
    <% end %>

    user name: <%= Order.user_name(@order) %><br>
    user email: <%= Order.user_email(@order) %><br>

    <%= number_to_currency(@order.total) %><br>
    status: <%= @order.status %><br>
    submitted: <%= @order.created_at %><br>
  </div>
</div>