config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :watch_items, only: [:edit, :create, :update, :index, :destroy]
  resources :orders
  resources :bids
  resources :pending_bids, only: [:create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/all_items', to: 'items#index'
  
  root 'staticpages#index'
  
  resources :stores
  
  namespace :stores, as: :store, path: '/:store' do 
    resources :items
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :bids
  has_many :user_roles
  has_many :roles, through: :user_roles

  validates :fullname, presence: true, length: {in: 2..32}
  validates :email, presence: true, length: { in: 5..50 },
            uniqueness: true
  VALID_REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_format_of :email, with: VALID_REGEX_EMAIL, on: :create
  validates :display_name, allow_blank: true, length: {in: 2..32}
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  validates_format_of :zipcode, :with => /\A^\d{5}(-\d{4})?$\z/, :multiline => true, :message => "should be in the form 12345 or 12345-1234"
  validates :credit_card, presence: true, length: { minimum: 15, maximum: 16 }
  validates :cc_expiration_date, presence: true

  before_validation :clean_credit_card  #callback's allow you to alter the data, then the validations check the updated results

  has_secure_password

  has_attached_file :avatar, styles: {thumb: '100x100>',
                                      square: '200x200#',
                                      medium: '300x300>'},
                              default_url: "beast2.png",
                              storage: :s3,
                              bucket: ENV['bucket'],
                              s3_credentials: { access_key_id: ENV['access_key_id'],
                                                secret_access_key: ENV['secret_access_key'] }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def platform_admin?
    roles.exists?(name: 'platform_admin')
  end

  def store_admin?
    roles.exists?(name: 'store_admin')
  end

  def registered_user?
    roles.exists?(name: 'registered_user')
  end 
  
  def store_slug
    Store.find(store_id).slug
  end
  
  def store
    Store.find(store_id)
  end

  protected
    def clean_credit_card
      credit_card.gsub!(/[^\d]/, "") unless credit_card.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      if @pending_bid.contents.empty?
        redirect_to users_path
      else
        Bid.create(user_id: current_user.id, item_id: @pending_bid.contents["bid"]["item"].to_i, current_price: @pending_bid.contents["bid"]["price"].to_i)
        flash[:success] = "Your bid successfully posted!"
        session[:pending_bid].clear
        redirect_to users_path
      end
    else
      flash[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to users_path
  end

  private

 def user_params
    params.require(:user).permit(:fullname,
                                 :display_name,
                                 :email,
                                 :phone,
                                 :password,
                                 :password_confirmation,
                                 :avatar, :street, :city, :state, :zipcode,
                                 :credit_card, :cc_expiration_date)
  end

end

app/views/users/_form.html.erb
<div class="stitched watch-list">
  <%= form_for(@user, url: users_path, multipart: true) do |f| %>

<p class="float-right move-down"> * required field </p>
<h3>Account Information</h3>

<div class="row-split">
  <div class="col-md-6">
    <%= f.label :full_name, "Full name *" %>
    <%= f.text_field :fullname,  autofocus: true%>
  </div>
</div>

<div class="row-spit">
  <div class="col-md-6">
    <%= f.label :display_name %>
    <%= f.text_field :display_name %>
  </div>
</div>

<div class="row-spit">
  <div class="col-md-4">
    <%= f.label :email, "Email *" %>
    <%= f.text_field :email %>
  </div>
</div>

<div class="row-split">
  <div class="col-md-4">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
</div>

<div class="row-split">
  <div class="col-md-4">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
</div>

<div class="split-row">
  <div class="col-md-6">
    <%= f.label :password, "Password *" %>
    <%= f.password_field :password %>
  </div>
</div>

<div class="split-row">
  <div class="col-md-6">
    <%= f.label :password_confirmation, "Password confirmation *"  %>
    <%= f.password_field :password_confirmation %>
  </div>
</div>


  <div class="col-md-10">
<div class="row align-log">

  <br><br><h3>Billing Information</h3>
  </div>
</div>
<div>

<div class="row-split">
  <div class="col-md-6">
    <%= f.label :street, "Street *" %>
    <%= f.text_field :street%>
  </div>
</div>

<div class="row-split">
  <div class="col-md-6">
    <%= f.label :apt_number %>
    <%= f.text_field :apt_number%>
  </div>
</div>

<div class="row-split">
  <div class="col-md-4">
    <%= f.label :city, "City *" %>
    <%= f.text_field :city%>
  </div>
</div>

<div class="row-spit">
  <div class="col-md-4">
    <%= f.label :state, "State *" %>
    <%= f.text_field :state%>
  </div>
</div>

<div class="row-spit">
  <div class="col-md-4">
    <%= f.label :zip_code, "Zipcode *" %>
    <%= f.text_field :zipcode%>
  </div>
</div>

<div class="row-spit">
  <div class="col-md-4">
    <%= f.label :credit_card, "Credit card *" %>
    <%= f.text_field :credit_card%>
  </div>
</div>

<div class="row-split">
  <div class="col-md-4 expiration-date">
   <%= f.label :expiration_date, "Expiration date *"%>
    <%= f.date_select :cc_expiration_date, start_year:Date.today.year, end_year: Date.today.year + 10, discard_day: true %>
  </div>
</div>

<div class="row align-login">
  <div class="col-md-12">
    <%= f.submit "Submit", :class => "btn btn-info" %><br><br>
    <%= link_to "Already a Member? Login", login_path %>
  </div>
</div>

  <% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  
  <h1 class="watch-list-header">Edit Profile</h1>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="watch-list-header">Sign Up</h2>
  <%= render'form' %>
</div>

app/views/users/show.html.erb
<div class="container">

  <% if current_user.display_name.blank? %>
    <h1 class="watch-list-header">Welcome, <%= current_user.fullname %>!</h1>
  <% else %>
    <h1 class="watch-list-header">Welcome, <%= current_user.display_name %>!</h1>
  <% end %>

  <div class="row user-info-row">
    
    <div class="col-md-2 ">
      <%= image_tag current_user.avatar.url %>
    </div>
    <% if current_user.bids.empty? %>
    <h3 ><%= link_to "Let the bidding begin! Check out our stores!", stores_path %></h3>
    <% else %>
    <div class="col-md-10 stitched watch-list">
    <table class="table-condensed">
      <tr>
        <th class="bid-button">Item</th>
        <th>Your Bid </th>
        <th>Time Remaining</th>
        <th>Highest Bid</th>
        <th class="bid-button">Re-bid!</th>
      </tr>
      
      <% current_user.bids.each do |bid| %>
      <tr>
        <% if !bid.item.expired? %>
        <td class="bid-button"><%= link_to bid.item.name, store_item_path(store: bid.item.store.slug, id: bid.item.id) %> </td>
        <td><%= number_to_currency(bid.current_price) %> </td>
        <td><%= distance_of_time_in_words(Time.now, bid.item.expiration_date) %> </td>
        <td> <%= number_to_currency(bid.item.highest_bid) %> </td>
        
        <% if bid.current_price < bid.item.highest_bid %>
    
            <td class="bid-button"> <%= form_for(:bid, url: bid_path(bid), method: :patch) do |f| %>
              <%= f.number_field :current_price, value: number_with_precision(bid.item.highest_bid + 1, precision: 2), :id => "bid-input", class: "number-center" %>
              <%= f.hidden_field :item_id, value: bid.item.id %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit "Bid Now"%> </td>
              <% end %>
            <% else %>
              <td>You're the highest bidder!</td>
              <% end %>
            <% end %>
        <% end %>
      </tr>
    </table>
  </div>
  <% end %>
  </div>

    <div class="row user-info-row">
       <div class="col-md-2">
          <%= link_to "Edit Profile", edit_users_path(@user) %> |
          <%= link_to "Past Orders", orders_path %>
      </div>
    </div>
</div>

      