config/routes.rb
Rails.application.routes.draw do
  resource :users
  resources :watch_items, only: [:edit, :create, :update, :index, :destroy]
  resources :orders
  resources :bids
  resources :pending_bids, only: [:create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/all_items', to: 'items#index'
  
  root 'staticpages#index'
  
  resources :stores
  
  namespace :stores, as: :store, path: '/:store' do 
    resources :items
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  belongs_to :store
  belongs_to :category
  has_many :bids
  
  validates :name, presence: true
  validates :description, presence: true
  validates :starting_price, presence: true
  validates :expiration_date, presence: true
  validates :store_id, presence: true
  validates :category_id, presence: true
  
  has_attached_file :attachment, default_url: "default-item.png",
                                 storage: :s3,
                                 bucket: ENV['bucket'],
                                 s3_credentials: { access_key_id: ENV["access_key_id"],
                                                   secret_access_key: ENV["secret_access_key"] }

  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
  
  def expired?
    expiration_date < Time.now
  end

  def highest_bid
    if bids.any?
      Bid.where(item_id: id).maximum(:current_price)
    else
      starting_price
    end
  end
  
  def highest_bidder_id
    Bid.where(item_id: id).order(current_price: :desc).first.user_id
  end

  def available?
    active == true
  end

  def time_in_seconds
    (expiration_date - (Time.now)).round
  end
  
  def store_slug
    Store.find(store_id).slug
  end

  def final_date
    expiration_date.strftime("%m/%d/%Y")
  end
end

app/models/store.rb
class Store < ActiveRecord::Base  
  validates :name, uniqueness: true,
                   presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug

  has_many :items

  def generate_slug
    self.slug = name.parameterize
  end

  def self.sort_all
    order(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @categories = Category.all
    @items = Item.all
  end
end

app/controllers/stores/items_controller.rb
class Stores::ItemsController < Stores::StoresController
  
  def index
    @items = Item.where(store_id: current_store.id).paginate(:page => params[:page], :per_page => 8)
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @categories = Category.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "Item has been created!"
      redirect_to store_items_path
    else
      flash.now[:errors] = @item.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def edit 
    @item = current_user.store.items.find(params[:id])
    @categories = Category.all
  end
  
  def update
    @item = current_user.store.items.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Item has been updated!"
      redirect_to store_items_path
    else
      flash.now[:errors] = @item.errors.full_messages.join(", ")
      render :edit
    end
  end
  
  def destroy
    item = current_user.store.items.find(params[:id])
    if item.bids.empty?
      item.delete
      flash[:success] = "Item has been deleted!"
      redirect_to store_items_path
    else
      flash[:errors] = "That item has bids! It can't be deleted."
      redirect_to store_items_path
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, 
                                 :description, 
                                 :active,
                                 :starting_price, 
                                 :expiration_date, 
                                 :attachment, 
                                 :category_id, 
                                 :store_id)
  end
end

app/controllers/stores/stores_controller.rb
class Stores::StoresController < ApplicationController
  helper_method :current_store
  
  def current_store
    @current_store ||= Store.find_by(slug: params[:store])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  def index
    @stores = Store.paginate(:page => params[:page], :per_page => 8)
  end
  
  def new
    @store = Store.new
  end
  
  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:success] = "Store was successfully created."
      redirect_to stores_path
    else
      flash.now[:errors] = @store.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def edit
    @store = Store.find(params[:id])
  end
  
  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      flash[:success] = "Store was successfully updated."
      redirect_to store_items_path(store: @store.slug)
    else
      flash.now[:errors] = @store.errors.full_messages.join(", ")
      render :edit
    end
  end
  
  def destroy
    store = Store.find(params[:id])
    store.delete
    flash[:success] = "Store was successfully deleted."
    redirect_to stores_path
  end

  private
  
  def store_params
    params.require(:store).permit(:name)
  end
end

app/helpers/stores/items_helper.rb
module Stores::ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/items/_form.html.erb
<%= form_for @item, url: store_item_path, multipart: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :active %>
  active <%= f.radio_button :active, "true" %>
  retired <%= f.radio_button :active, "false" %><br>

  <%= f.label :starting_price %>
  <%= f.number_field :starting_price %>

  <%= f.label :expiration_date %>
  <%= f.datetime_local_field :expiration_date %>
  
  <%= f.label :attachment %>
  <%= f.file_field :attachment %><br>

  <p>Category:</p>
  <ul >
  <%= f.collection_select(:category_id, @categories.to_a, :id, :name) %>
  </ul>

  <%= f.hidden_field :store_id, value: current_user.store_id %>
  <%= f.submit %>
<% end %>

app/views/stores/items/edit.html.erb
<div class="container">
  <h1 class="watch-list-header">Update Item</h1>
  <div class="stitched watch-list">
    <%= render 'form'  %>
  </div>
</div>

app/views/stores/items/index.html.erb
<div class="row">
  <div class="col-md-12 store-column">
    <h1 id="stores-header"> <%= current_store.name %></h1>
  </div>
</div>

<div class="container">
  <% @items.each_slice(4) do |four_items| %>

    <div class="row">
      <% four_items.each do |item| %>
        <div class="col-md-3">

          <div class="well well-items">
            <h5 class="items-title"> <%= link_to item.name, store_item_path(item, id: item.id) %> </h5>
            <%= link_to image_tag(item.attachment.url, class: "image-border"), store_item_path(item.store.slug, item) %>
            
            <%if item.expired? %>
              <p class="black-font">No longer available<br>
                <em>Final price: </em><%= number_to_currency(item.highest_bid) %><br> 
                <em>Expired: </em> <%= item.final_date %>
              </p>
            <% else %>
              <p class="time less-margin"><%= distance_of_time_in_words(Time.now, item.expiration_date) %> remaining<br> current bid: <%= number_to_currency(item.highest_bid) %></p>

              <% if store_admin? && item.store_id.to_i == current_user.store_id.to_i %>
                  <%= link_to "Edit", edit_store_item_path(id: item.store_id) %> 
                  <%= link_to "Delete", store_item_path(id: item.store_id), method: "delete" %>   
                  
              <% elsif current_user && Bid.bid_exsits?(current_user.id, item.id) %>
                <%= link_to "View your bid standing.", users_path(current_user)  %>
              <% elsif current_user %>   

                <%= form_for(:bid, url: :bids, class: "less-margin", method: :post) do |f| %>
                  <%= f.number_field :current_price, min: number_with_precision(item.highest_bid + 1), step: 1.00, value: number_with_precision(item.highest_bid + 1, precision: 2), :id => "bid-input", class: "number-center" %>
                  <%= f.label :minimum_bid, :id => 'minimum-bid' %>
                  <%= f.hidden_field :item_id, value: item.id %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.submit "Bid Now", class: "btn btn-primary float-left" %>
                <% end %>

                  <%= form_for(:order, url: :watch_items) do |f| %>
                    <%= f.hidden_field :item_id, value: item.id %>
                    <%= f.hidden_field :item_price, value: item.highest_bid %>
                    <%= f.submit "Watch", url: watch_items_path, class: "btn btn-info float-right" %>
                  <% end %>
                  

                <% else %>

                <%= form_for(:bid, url: :pending_bids, class: "less-margin" ) do |f| %>
                  <%= f.number_field :current_price, min: number_with_precision(item.highest_bid + 1), step: 1.00, value: number_with_precision(item.highest_bid + 1, precision: 2), :id => "bid-input", class: "number-center" %>
                  <%= f.label :minimum_bid, :id => 'minimum-bid' %>
                  <%= f.hidden_field :item_id, value: item.id %>
                  <%= f.submit "Bid Now", :class => "btn btn-primary float-left" %>
                <% end %>

                <%= form_for(:order, url: :watch_items) do |f| %>
                  <%= f.hidden_field :item_id, value: item.id %>
                  <%= f.hidden_field :item_price, value: item.highest_bid %>
                  <%= f.submit "Watch", url: watch_items_path, class: "btn btn-info float-right" %>
                <% end %>

              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  
  <%= will_paginate %>
</div>

app/views/stores/items/new.html.erb
<div class="container">
  <h1 class="watch-list-header">Create Item</h1>
  <div class="stitched watch-list">
  <%= form_for @item, url: store_items_path, multipart: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :active %>
    active <%= f.radio_button :active, "true" %>
    retired <%= f.radio_button :active, "false" %><br>

    <%= f.label :starting_price %>
    <%= f.number_field :starting_price %>

    <%= f.label :expiration_date %>
    <%= f.datetime_local_field :expiration_date %>
    
    <%= f.label :attachment %>
    <%= f.file_field :attachment %><br>

    <p>Category:</p>
    <ul >
    <%= f.collection_select(:category_id, @categories.to_a, :id, :name) %>
    </ul>

    <%= f.hidden_field :store_id, value: current_user.store_id %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/stores/items/show.html.erb
<div class="row">
<div class="text-center col-md-12 store-column">
  <h1 id="stores-header">
    <%= @item.name %><br>
    <small>
      <%if @item.expired? %>
      <p>This Item is no longer available</p>
      <% else %>
        <% if @item.time_in_seconds <= 85400 %>
          <div class="your-clock col-md-offset-5", id="clock">
          </div>
          <div class="remaining-time hidden">
            <%= @item.time_in_seconds %>
          </div>
          <% else %>
            <%= distance_of_time_in_words(Time.now, @item.expiration_date) %> remaining | current bid: <%= number_to_currency(@item.highest_bid) %>
          <% end %>

    <% end %>
    </small>
  </h1>
</div>
</div>

 <%if @item.expired? %>
    <div class="row text-center" >
      <div class="col-md-12">
        <%= image_tag(@item.attachment.url, :id => "item-show-image", width: "450", class: "image-border") %>
        <h5 class="item-description"> <%= @item.description %></h5>
        <p class="item-description"><strong>Category:</strong> <%= @item.category.name %> <br>
        <em><strong>Final price: </em></strong><%= number_to_currency(@item.highest_bid) %><br> 
        <em><strong>Expired: </em></strong> <%= @item.final_date %></p>
      </div>
    </div>
    <% else %>
    <div class="row text-center" >
      <div class="col-md-12">
        <%= image_tag(@item.attachment.url, :id => "item-show-image", width: "450", class: "image-border") %>
        <h5 class="item-description"> <%= @item.description %></h5>
        <p class="item-description"><strong>Category:</strong> <%= @item.category.name %> </p>
      </div>
    </div>


<div class="row">
  <div class="col-md-4 col-md-offset-4 item-show-buttons number-center">
  <% if current_user && Bid.bid_exsits?(current_user.id, @item.id)%>
    <%= link_to "View your bid standing", users_path(current_user) %>

  <% elsif current_user %>  

    <%= form_for(:bid, url: :bids, method: :post) do |f| %>

      <%= f.number_field :current_price, min: number_with_precision(@item.highest_bid + 1), step: 1.00, value: number_with_precision(@item.highest_bid + 1, precision: 2), :id => "bid-input", class: "number-center" %>
      <%= f.label :minimum_bid, :id => 'minimum-bid', class: "number-center" %>
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Bid Now", class: "btn btn-primary float-left" %>
    <% end %>

    <%= form_for(:order, url: :watch_items) do |f| %>
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.hidden_field :item_price, value: @item.highest_bid %>
      <%= f.submit "Watch", url: watch_items_path, class: "btn btn-info float-right" %>
    <% end %>

  <% else %>
    
    <%= form_for(:bid, url: :pending_bids) do |f| %>
      <%= f.number_field :current_price, min: number_with_precision(@item.highest_bid + 1), step: 1.00, value: number_with_precision(@item.highest_bid + 1, precision: 2), :id => "bid-input", class: "number-center" %>
      <%= f.label :minimum_bid, :id => 'minimum-bid',class: "number-center" %>
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.submit "Bid Now", class: "btn btn-primary float-left" %>
    <% end %>

    <%= form_for(:order, url: :watch_items) do |f| %>
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.hidden_field :item_price, value: @item.highest_bid %>
      <%= f.submit "Watch", url: watch_items_path, class: "btn btn-info float-right" %>
    <% end %>

<% end %>
<% end %>



  